from Register import U32, U64, STR32, S32, S16, U16

from modbusreader import ModbusReader


def add_tripower_register(wr: ModbusReader):
    wr.add_register(U32(30051, 3, "Nameplate.MainModel", "Geräteklasse"))
    wr.add_register(U32(30053, 3, "Nameplate.Model", "Gerätetyp"))
    wr.add_register(U32(30055, 3, "Nameplate.Vendor", "Hersteller"))
    wr.add_register(U32(30057, 3, "Nameplate.SerNum", "Seriennummer"))
    wr.add_register(U32(30059, 3, "Nameplate.PkgRev", "Softwarepaket"))
    wr.add_register(U32(30199, 3, "Operation.RmgTms", "Wartezeit bis Einspeisung"))
    wr.add_register(U32(30201, 3, "Operation.Health", "Zustand"))
    wr.add_register(U32(30203, 3, "Operation.HealthStt.Ok", "Nennleistung im Zustand Ok"))
    wr.add_register(U32(30205, 3, "Operation.HealthStt.Wrn", "Nennleistung im Zustand Warnung"))
    wr.add_register(U32(30207, 3, "Operation.HealthStt.Alm", "Nennleistung im Zustand Fehler"))
    wr.add_register(U32(30211, 3, "Operation.Evt.Prio", "Empfohlene Aktion"))
    wr.add_register(U32(30213, 3, "Operation.Evt.Msg", "Meldung"))
    wr.add_register(U32(30215, 3, "Operation.Evt.Dsc", "Fehlerbehebungsmaßnahme"))
    wr.add_register(U32(30217, 3, "Operation.GriSwStt", "Netzrelais/-schütz"))
    wr.add_register(U32(30219, 3, "Operation.DrtStt", "Leistungsreduzierung"))
    wr.add_register(U32(30225, 3, "Isolation.LeakRis", "Isolationswiderstand"))
    wr.add_register(U32(30231, 3, "Inverter.WLim", "Maximale Gerätewirkleistung"))
    wr.add_register(U32(30233, 3, "Inverter.WMax", "Eingestellte Wirkleistungsgrenze"))
    wr.add_register(U32(30247, 3, "Operation.Evt.EvtNo", "Aktuelle Ereignisnummer für Hersteller"))
    wr.add_register(U64(30513, 3, "Metering.TotWhOut", "Gesamtertrag"))
    wr.add_register(U64(30521, 3, "Metering.TotOpTms", "Betriebszeit"))
    wr.add_register(U64(30525, 3, "Metering.TotFeedTms", "Einspeisezeit"))
    wr.add_register(U32(30529, 3, "Metering.TotWhOut", "Gesamtertrag Wh"))
    wr.add_register(U32(30531, 3, "Metering.TotWhOut", "Gesamtertrag kWh"))
    wr.add_register(U32(30533, 3, "Metering.TotWhOut", "Gesamtertrag MWh"))
    wr.add_register(U32(30541, 3, "Metering.TotOpTms", "Betriebszeit"))
    wr.add_register(U32(30543, 3, "Metering.TotFeedTms", "Einspeisezeit"))
    wr.add_register(U32(30559, 3, "Operation.EvtCntUsr", "Anzahl Ereignisse für Benutzer"))
    wr.add_register(U32(30561, 3, "Operation.EvtCntIstl", "Anzahl Ereignisse für Installateur"))
    wr.add_register(U32(30563, 3, "Operation.EvtCntSvc", "Anzahl Ereignisse für Service"))
    wr.add_register(U32(30581, 3, "Metering.GridMs.TotWhIn", "Zählerstand Bezugszähler"))
    wr.add_register(U32(30583, 3, "Metering.GridMs.TotWhOut", "Zählerstand Einspeisezähler"))
    wr.add_register(U32(30599, 3, "Operation.GriSwCnt", "Anzahl Netzzuschaltungen"))
    wr.add_register(S32(30769, 3, "DcMs.Amp", "DC Strom Eingang"))
    wr.add_register(S32(30771, 3, "DcMs.Vol", "DC Spannung Eingang"))
    wr.add_register(S32(30773, 3, "DcMs.Watt", "DC Leistung Eingang"))
    wr.add_register(S32(30775, 3, "GridMs.TotW", "Leistung"))
    wr.add_register(S32(30777, 3, "GridMs.W.phsA", "Leistung L1"))
    wr.add_register(S32(30779, 3, "GridMs.W.phsB", "Leistung L2"))
    wr.add_register(S32(30781, 3, "GridMs.W.phsC", "Leistung L3"))
    wr.add_register(U32(30783, 3, "GridMs.PhV.phsA", "Netzspannung Phase L1"))
    wr.add_register(U32(30785, 3, "GridMs.PhV.phsB", "Netzspannung Phase L2"))
    wr.add_register(U32(30787, 3, "GridMs.PhV.phsC", "Netzspannung Phase L3"))
    wr.add_register(U32(30789, 3, "GridMs.PhV.phsA2B", "Netzspannung Phase L1 gegen L2"))
    wr.add_register(U32(30791, 3, "GridMs.PhV.phsB2C", "Netzspannung Phase L2 gegen L3"))
    wr.add_register(U32(30793, 3, "GridMs.PhV.phsC2A", "Netzspannung Phase L3 gegen L1"))
    wr.add_register(U32(30795, 3, "GridMs.TotA", "Netzstrom"))
    wr.add_register(U32(30803, 3, "GridMs.Hz", "Netzfrequenz"))
    wr.add_register(S32(30805, 3, "GridMs.TotVAr", "Blindleistung"))
    wr.add_register(S32(30807, 3, "GridMs.VAr.phsA", "Blindleistung L1"))
    wr.add_register(S32(30809, 3, "GridMs.VAr.phsB", "Blindleistung L2"))
    wr.add_register(S32(30811, 3, "GridMs.VAr.phsC", "Blindleistung L3"))
    wr.add_register(S32(30813, 3, "GridMs.TotVA", "Scheinleistung"))
    wr.add_register(S32(30815, 3, "GridMs.VA.phsA", "Scheinleistung L1"))
    wr.add_register(S32(30817, 3, "GridMs.VA.phsB", "Scheinleistung L2"))
    wr.add_register(S32(30819, 3, "GridMs.VA.phsC", "Scheinleistung L3"))
    wr.add_register(U32(30825, 3, "Inverter.VArModCfg.VArMod", "Betriebsart der statischen Spannungshaltung, Konfiguration der statischen Spannungshaltung"))
    wr.add_register(S32(30829, 3, "Inverter.VArModCfg.VArCnstCfg.VArNom", "Blindleistungssollwert in %"))
    wr.add_register(S32(30831, 3, "Inverter.VArModCfg.PFCnstCfg.PF", "Sollwert des cos Phi, Konfiguration des cos Phi, direkte Vorgabe"))
    wr.add_register(U32(30833, 3, "Inverter.VArModCfg.PFCnstCfg.PFExt", "Erregungsart des cos Phi, Konfiguration des cos Phi, direkte Vorgabe"))
    wr.add_register(U32(30835, 3, "Inverter.WModCfg.WMod", "Betriebsart des Einspeisemanagements"))
    wr.add_register(U32(30837, 3, "Inverter.WModCfg.WCnstCfg.W", "Wirkleistungsbegrenzung in W"))
    wr.add_register(U32(30839, 3, "Inverter.WModCfg.WCnstCfg.WNom", "Wirkleistungsbegrenzung in %"))
    wr.add_register(S32(30865, 3, "Metering.GridMs.TotWIn", "Leistung Bezug"))
    wr.add_register(S32(30867, 3, "Metering.GridMs.TotWOut", "Leistung Einspeisung"))
    wr.add_register(U32(30875, 3, "MltFncSw.Stt", "Status des Multifunktionsrelais"))
    wr.add_register(U32(30881, 3, "Operation.PvGriConn", "Netzanbindung der Anlage"))
    wr.add_register(U32(30925, 3, "Spdwr.ComSocA.ConnSpd", "Verbindungsgeschwindigkeit von SMACOM A"))
    wr.add_register(U32(30927, 3, "Spdwr.ComSocA.DpxMode", "Duplexmodus von SMACOM A"))
    wr.add_register(U32(30929, 3, "Spdwr.ComSocA.Stt", "Speedwire-Verbindungsstatus von SMACOM A"))
    wr.add_register(U32(30931, 3, "Spdwr.ComSocB.ConnSpd", "Verbindungsgeschwindigkeit von SMACOM B"))
    wr.add_register(U32(30933, 3, "Spdwr.ComSocB.DpxMode", "Duplexmodus von SMACOM B"))
    wr.add_register(U32(30935, 3, "Spdwr.ComSocB.Stt", "Speedwire-Verbindungsstatus von SMACOM B"))
    wr.add_register(U32(30949, 3, "GridMs.TotPFPrc", "Verschiebungsfaktor"))
    wr.add_register(S32(30953, 3, "Coolsys.Cab.TmpVal", "Innentemperatur"))
    wr.add_register(S32(30957, 3, "DcMs.Amp", "DC Strom Eingang"))
    wr.add_register(S32(30959, 3, "DcMs.Vol", "DC Spannung Eingang"))
    wr.add_register(S32(30961, 3, "DcMs.Watt", "DC Leistung Eingang"))
    wr.add_register(S32(30975, 3, "Inverter.DclVol", "Zwischenkreisspannung"))
    wr.add_register(S32(30977, 3, "GridMs.A.phsA", "Netzstrom Phase L1"))
    wr.add_register(S32(30979, 3, "GridMs.A.phsB", "Netzstrom Phase L2"))
    wr.add_register(S32(30981, 3, "GridMs.A.phsC", "Netzstrom Phase L3"))
    wr.add_register(STR32(31017, 3, "Spdwr.ActlIp", "-"))
    wr.add_register(STR32(31025, 3, "Spdwr.ActlSnetMsk", "-"))
    wr.add_register(STR32(31033, 3, "Spdwr.ActlGwIp", "-"))
    wr.add_register(STR32(31041, 3, "Spdwr.ActlDnsSrvIp", "-"))
    wr.add_register(U32(31061, 3, "Bat.ChaCtlComAval", "Steuerung der Batterieladung über Kommunikation verfügbar"))
    wr.add_register(U32(31085, 3, "Operation.HealthStt.Ok", "Nennleistung im Zustand Ok"))
    wr.add_register(S32(31159, 3, "Operation.Dmd.VArCtl", "Aktuelle Vorgabe Blindleistung Q"))
    wr.add_register(S32(31221, 3, "GridMs.TotPFEEI", "EEI-Verschiebungsfaktor"))
    wr.add_register(S32(31247, 3, "Isolation.FltA", "Fehlerstrom"))
    wr.add_register(U32(31253, 3, "Metering.GridMs.PhV.phsA", "Netzspannung Phase L1"))
    wr.add_register(U32(31255, 3, "Metering.GridMs.PhV.phsB", "Netzspannung Phase L2"))
    wr.add_register(U32(31257, 3, "Metering.GridMs.PhV.phsC", "Netzspannung Phase L3"))
    wr.add_register(U32(31259, 3, "Metering.GridMs.W.phsA", "Leistung Netzeinspeisung L1"))
    wr.add_register(U32(31261, 3, "Metering.GridMs.W.phsB", "Leistung Netzeinspeisung L2"))
    wr.add_register(U32(31263, 3, "Metering.GridMs.W.phsC", "Leistung Netzeinspeisung L3"))
    wr.add_register(U32(31265, 3, "Metering.GridMs.WIn.phsA", "Leistung Netzbezug Phase L1"))
    wr.add_register(U32(31267, 3, "Metering.GridMs.WIn.phsB", "Leistung Netzbezug Phase L2"))
    wr.add_register(U32(31269, 3, "Metering.GridMs.WIn.phsC", "Leistung Netzbezug Phase L3"))
    wr.add_register(S32(31271, 3, "Metering.GridMs.VAr.phsA", "Blindleistung Netzeinspeisung Phase L1"))
    wr.add_register(S32(31273, 3, "Metering.GridMs.VAr.phsB", "Blindleistung Netzeinspeisung Phase L2"))
    wr.add_register(S32(31275, 3, "Metering.GridMs.VAr.phsC", "Blindleistung Netzeinspeisung Phase L3"))
    wr.add_register(S32(31277, 3, "Metering.GridMs.TotVAr", "Blindleistung Netzeinspeisung"))
    wr.add_register(U32(31405, 3, "Operation.Dmd.WCtl", "Aktuelle Vorgabe Wirkleistungsbegrenzung P"))
    wr.add_register(U32(31407, 3, "Operation.Dmd.PFCtl", "Aktuelle Vorgabe cos Phi"))
    wr.add_register(U32(31409, 3, "Operation.Dmd.PFExtCtl", "Aktuelle Vorgabe Erregungsart cos Phi"))
    wr.add_register(S32(31411, 3, "Operation.Dmd.VArCtl", "Aktuelle Vorgabe Blindleistung Q"))
    wr.add_register(S32(31793, 3, "DcMs.Amp", "DC Strom Eingang"))
    wr.add_register(S32(31795, 3, "DcMs.Amp", "DC Strom Eingang"))
    wr.add_register(S32(34113, 3, "Coolsys.Cab.TmpVal", "Innentemperatur"))
    wr.add_register(S32(34609, 3, "Env.TmpVal", "Außentemperatur"))
    wr.add_register(S32(34611, 3, "Env.TmpValMax", "Höchste gemessene Außentemperatur"))
    wr.add_register(U32(34615, 3, "Env.HorWSpd", "Windgeschwindigkeit"))
    wr.add_register(S32(34621, 3, "Mdul.TmpVal", "Modultemperatur"))
    wr.add_register(U32(34623, 3, "Env.ExInsol", "Einstrahlung auf externen Sensor"))
    wr.add_register(S32(34625, 3, "Env.TmpVal", "Außentemperatur"))
    wr.add_register(S32(34627, 3, "Env.TmpVal", "Außentemperatur"))
    wr.add_register(S32(34629, 3, "Mdul.TmpVal", "Modultemperatur"))
    wr.add_register(S32(34631, 3, "Mdul.TmpVal", "Modultemperatur"))
    wr.add_register(U32(34633, 3, "Env.HorWSpd", "Windgeschwindigkeit"))
    wr.add_register(U32(34635, 3, "Env.HorWSpd", "Windgeschwindigkeit"))
    wr.add_register(U32(34669, 3, "Bat.ChaCtlComAval", "Steuerung der Batterieladung über Kommunikation verfügbar"))
    wr.add_register(U64(35377, 3, "Operation.EvtCntUsr", "Anzahl Ereignisse für Benutzer"))
    wr.add_register(U64(35381, 3, "Operation.EvtCntIstl", "Anzahl Ereignisse für Installateur"))
    wr.add_register(U64(35385, 3, "Operation.EvtCntSvc", "Anzahl Ereignisse für Service"))
    wr.add_register(U32(40003, 3, "DtTm.TmZn", "Zeitzone"))
    wr.add_register(U32(40005, 3, "DtTm.DlSvIsOn", "Automatische Sommer-/Winterzeitumstellung eingeschaltet"))
    wr.add_register(U32(40009, 3, "Operation.OpMod", "Betriebszustand"))
    wr.add_register(U32(40013, 3, "CntrySettings.Lang", "Sprache der Oberfläche"))
    wr.add_register(S16(40015, 3, "Inverter.VArModCfg.VArCtlComCfg.VArNom", "Normierte Blindleistungsvorgabe durch Anlagensteuerung"))
    wr.add_register(S16(40016, 3, "Inverter.WModCfg.WCtlComCfg.WNom", "Normierte Wirkleistungsbegrenzung durch Anlagensteuerung"))
    wr.add_register(U32(40018, 3, "Inverter.FstStop", "Schnellabschaltung"))
    wr.add_register(S16(40022, 3, "Inverter.VArModCfg.VArCtlComCfg.VArNomPrc", "Normierte Blindleistungsbegrenzung durch Anlagensteuerung"))
    wr.add_register(S16(40023, 3, "Inverter.WModCfg.WCtlComCfg.WNomPrc", "Normierte Wirkleistungsbegrenzung durch Anlagensteuerung"))
    wr.add_register(U16(40024, 3, "Inverter.VArModCfg.PFCtlComCfg.PF", "Verschiebungsfaktor durch Anlagensteuerung"))
    wr.add_register(U32(40025, 3, "Inverter.VArModCfg.PFCtlComCfg.PFExt", "Erregungsart durch Anlagensteuerung"))
    wr.add_register(U32(40029, 3, "Operation.OpStt", "Betriebsstatus"))
    wr.add_register(U32(40063, 3, "Nameplate.CmpMain.SwRev", "Firmware-Version des Hauptprozessors"))
    wr.add_register(U32(40067, 3, "Nameplate.SerNum", "Seriennummer"))
    wr.add_register(U32(40077, 3, "Sys.DevRstr", "Geräteneustart auslösen"))
    wr.add_register(U32(40095, 3, "GridGuard.Cntry.VolCtl.Max", "Spannungsüberwachung obere Maximalschwelle"))
    wr.add_register(U32(40109, 3, "GridGuard.Cntry", "Eingestellte Ländernorm"))
    wr.add_register(U32(40133, 3, "GridGuard.Cntry.VRtg", "Netz-Nennspannung"))
    wr.add_register(U32(40135, 3, "GridGuard.Cntry.HzRtg", "Nennfrequenz"))
    wr.add_register(S32(40149, 3, "Inverter.WModCfg.WCtlComCfg.WSpt", "Wirkleistungsvorgabe"))
    wr.add_register(U32(40151, 3, "Inverter.WModCfg.WCtlComCfg.WCtlComAct", "Wirk- und Blindleistungsregelung über Kommunikation"))
    wr.add_register(U32(40157, 3, "Spdwr.AutoCfgIsOn", "Automatische Speedwire-Konfiguration eingeschaltet"))
    wr.add_register(STR32(40159, 3, "Spdwr.Ip", "-"))
    wr.add_register(STR32(40167, 3, "Spdwr.SnetMsk", "-"))
    wr.add_register(STR32(40175, 3, "Spdwr.GwIp", "-"))
    wr.add_register(U32(40185, 3, "Inverter.VALim", "Maximale Gerätescheinleistung"))
    wr.add_register(U32(40195, 3, "Inverter.VAMax", "Eingestellte Scheinleistungsgrenze"))
    wr.add_register(U32(40200, 3, "Inverter.VArModCfg.VArMod", "Betriebsart der statischen Spannungshaltung, Konfiguration der statischen Spannungshaltung"))
    wr.add_register(S32(40204, 3, "Inverter.VArModCfg.VArCnstCfg.VArNom", "Blindleistungssollwert in %"))
    wr.add_register(S32(40206, 3, "Inverter.VArModCfg.PFCnstCfg.PF", "Sollwert des cos Phi, Konfiguration des cos Phi, direkte Vorgabe"))
    wr.add_register(U32(40208, 3, "Inverter.VArModCfg.PFCnstCfg.PFExt", "Erregungsart des cos Phi, Konfiguration des cos Phi, direkte Vorgabe"))
    wr.add_register(U32(40210, 3, "Inverter.WModCfg.WMod", "Betriebsart des Einspeisemanagements"))
    wr.add_register(U32(40212, 3, "Inverter.WModCfg.WCnstCfg.W", "Wirkleistungsbegrenzung in W"))
    wr.add_register(U32(40214, 3, "Inverter.WModCfg.WCnstCfg.WNom", "Wirkleistungsbegrenzung in %"))
    wr.add_register(U32(40216, 3, "Inverter.WCtlHzModCfg.WCtlHzMod", "Betriebsart der Wirkleistungsreduktion bei Überfrequenz P(f)"))
    wr.add_register(U32(40218, 3, "Inverter.WCtlHzModCfg.WCtlHzCfg.HzStr", "Abstand der Startfrequenz zur Netzfrequenz, Konfiguration des linearen Gradienten der Momentanleistung"))
    wr.add_register(U32(40220, 3, "Inverter.WCtlHzModCfg.WCtlHzCfg.HzStop", "Abstand der Rücksetzfrequenz zur Netzfrequenz, Konfiguration des linearen Gradienten der Momentanleistung"))
    wr.add_register(U32(40222, 3, "Inverter.VArModCfg.PFCtlWCfg.PFStr", "cos Phi des Startpunktes, Konfiguration der cos Phi(P)-Kennlinie"))
    wr.add_register(U32(40224, 3, "Inverter.VArModCfg.PFCtlWCfg.PFExtStr", "Erregungsart des Startpunktes, Konfiguration der cos Phi(P)-Kennlinie"))
    wr.add_register(U32(40226, 3, "Inverter.VArModCfg.PFCtlWCfg.PFStop", "cos Phi des Endpunktes, Konfiguration der cos Phi(P)-Kennlinie"))
    wr.add_register(U32(40228, 3, "Inverter.VArModCfg.PFCtlWCfg.PFExtStop", "Erregungsart des Endpunktes, Konfiguration der cos Phi(P)-Kennlinie"))
    wr.add_register(U32(40230, 3, "Inverter.VArModCfg.PFCtlWCfg.WNomStr", "Wirkleistung des Startpunktes, Konfiguration der cos Phi(P)-Kennlinie"))
    wr.add_register(U32(40232, 3, "Inverter.VArModCfg.PFCtlWCfg.WNomStop", "Wirkleistung des Endpunktes, Konfiguration der cos Phi(P)-Kennlinie"))
    wr.add_register(U32(40234, 3, "Inverter.WGra", "Wirkleistungsgradient"))
    wr.add_register(U32(40238, 3, "Inverter.WCtlHzModCfg.WCtlHzCfg.WGra", "Wirkleistungsgradient, Konfiguration des linearen Gradienten der Momentanleistung"))
    wr.add_register(U32(40240, 3, "Inverter.WCtlHzModCfg.WCtlHzCfg.HystEna", "Aktivierung der Schleppzeigerfunktion, Konfiguration des linearen Gradienten der Momentanleistung"))
    wr.add_register(U32(40242, 3, "Inverter.WCtlHzModCfg.WCtlHzCfg.HzStopWGra", "Wirkleistungsgradient nach Rücksetzfrequenz, Konfiguration des linearen Gradienten der Momentanleistung"))
    wr.add_register(U32(40244, 3, "Inverter.DGSModCfg.DGSFlCfg.ArGraMod", "Blindstromstatik, Konfiguration der vollständigen dynamischen Netzstützung"))
    wr.add_register(U32(40246, 3, "Inverter.DGSModCfg.DGSFlCfg.ArGraSag", "Gradient K der Blindstromstatik für Unterpannung bei dynamischer Netzstützung"))
    wr.add_register(U32(40248, 3, "Inverter.DGSModCfg.DGSFlCfg.ArGraSwell", "Gradient K der Blindstromstatik für Überpannung bei dynamischer Netzstützung"))
    wr.add_register(U32(40250, 3, "Inverter.DGSModCfg.DGSMod", "Betriebsart der dynamischen Netzstützung, Konfiguration der dynamischen Netzstützung"))
    wr.add_register(S32(40252, 3, "Inverter.DGSModCfg.DGSFlCfg.DbVolNomMin", "Untergrenze Spannungstotband, Konfiguration der vollständigen dynamischen Netzstützung"))
    wr.add_register(U32(40254, 3, "Inverter.DGSModCfg.DGSFlCfg.DbVolNomMax", "Obergrenze Spannungstotband, Konfiguration der vollständigen dynamischen Netzstützung"))
    wr.add_register(U32(40256, 3, "Inverter.DGSModCfg.PwrCirInopVolNom", "PWM-Sperrspannung, Konfiguration der dynamischen Netzstützung"))
    wr.add_register(U32(40258, 3, "Inverter.DGSModCfg.PwrCirInopTms", "PWM-Sperrverzögerung, Konfiguration der dynamischen Netzstützung"))
    wr.add_register(U32(40262, 3, "Inverter.UtilCrvCfg.Crv0.NumPt", "Kennlinie, Anzahl der zu verwendenden Punkte der Kennlinie"))
    wr.add_register(U32(40264, 3, "Inverter.UtilCrvCfg.Crv0.NumPt", "Kennlinie, Anzahl der zu verwendenden Punkte der Kennlinie"))
    wr.add_register(U32(40266, 3, "Inverter.UtilCrvCfg.Crv0.NumPt", "Kennlinie, Anzahl der zu verwendenden Punkte der Kennlinie"))
    wr.add_register(S32(40282, 3, "Inverter.UtilCrvCfg.CrvPt1.XVal", "X-Werte der Kennlinie 1"))
    wr.add_register(S32(40284, 3, "Inverter.UtilCrvCfg.CrvPt1.XVal", "X-Werte der Kennlinie 1"))
    wr.add_register(S32(40286, 3, "Inverter.UtilCrvCfg.CrvPt1.XVal", "X-Werte der Kennlinie 1"))
    wr.add_register(S32(40288, 3, "Inverter.UtilCrvCfg.CrvPt1.XVal", "X-Werte der Kennlinie 1"))
    wr.add_register(S32(40290, 3, "Inverter.UtilCrvCfg.CrvPt1.XVal", "X-Werte der Kennlinie 1"))
    wr.add_register(S32(40292, 3, "Inverter.UtilCrvCfg.CrvPt1.XVal", "X-Werte der Kennlinie 1"))
    wr.add_register(S32(40294, 3, "Inverter.UtilCrvCfg.CrvPt1.XVal", "X-Werte der Kennlinie 1"))
    wr.add_register(S32(40296, 3, "Inverter.UtilCrvCfg.CrvPt1.XVal", "X-Werte der Kennlinie 1"))
    wr.add_register(S32(40306, 3, "Inverter.UtilCrvCfg.CrvPt1.YVal", "Y-Werte der Kennlinie 1"))
    wr.add_register(S32(40308, 3, "Inverter.UtilCrvCfg.CrvPt1.YVal", "Y-Werte der Kennlinie 1"))
    wr.add_register(S32(40310, 3, "Inverter.UtilCrvCfg.CrvPt1.YVal", "Y-Werte der Kennlinie 1"))
    wr.add_register(S32(40312, 3, "Inverter.UtilCrvCfg.CrvPt1.YVal", "Y-Werte der Kennlinie 1"))
    wr.add_register(S32(40314, 3, "Inverter.UtilCrvCfg.CrvPt1.YVal", "Y-Werte der Kennlinie 1"))
    wr.add_register(S32(40316, 3, "Inverter.UtilCrvCfg.CrvPt1.YVal", "Y-Werte der Kennlinie 1"))
    wr.add_register(S32(40318, 3, "Inverter.UtilCrvCfg.CrvPt1.YVal", "Y-Werte der Kennlinie 1"))
    wr.add_register(S32(40320, 3, "Inverter.UtilCrvCfg.CrvPt1.YVal", "Y-Werte der Kennlinie 1"))
    wr.add_register(S32(40330, 3, "Inverter.UtilCrvCfg.CrvPt2.XVal", "X-Werte der Kennlinie 2"))
    wr.add_register(S32(40332, 3, "Inverter.UtilCrvCfg.CrvPt2.XVal", "X-Werte der Kennlinie 2"))
    wr.add_register(S32(40334, 3, "Inverter.UtilCrvCfg.CrvPt2.XVal", "X-Werte der Kennlinie 2"))
    wr.add_register(S32(40336, 3, "Inverter.UtilCrvCfg.CrvPt2.XVal", "X-Werte der Kennlinie 2"))
    wr.add_register(S32(40338, 3, "Inverter.UtilCrvCfg.CrvPt2.XVal", "X-Werte der Kennlinie 2"))
    wr.add_register(S32(40340, 3, "Inverter.UtilCrvCfg.CrvPt2.XVal", "X-Werte der Kennlinie 2"))
    wr.add_register(S32(40342, 3, "Inverter.UtilCrvCfg.CrvPt2.XVal", "X-Werte der Kennlinie 2"))
    wr.add_register(S32(40344, 3, "Inverter.UtilCrvCfg.CrvPt2.XVal", "X-Werte der Kennlinie 2"))
    wr.add_register(S32(40354, 3, "Inverter.UtilCrvCfg.CrvPt2.YVal", "Y-Werte der Kennlinie 2"))
    wr.add_register(S32(40356, 3, "Inverter.UtilCrvCfg.CrvPt2.YVal", "Y-Werte der Kennlinie 2"))
    wr.add_register(S32(40358, 3, "Inverter.UtilCrvCfg.CrvPt2.YVal", "Y-Werte der Kennlinie 2"))
    wr.add_register(S32(40360, 3, "Inverter.UtilCrvCfg.CrvPt2.YVal", "Y-Werte der Kennlinie 2"))
    wr.add_register(S32(40362, 3, "Inverter.UtilCrvCfg.CrvPt2.YVal", "Y-Werte der Kennlinie 2"))
    wr.add_register(S32(40364, 3, "Inverter.UtilCrvCfg.CrvPt2.YVal", "Y-Werte der Kennlinie 2"))
    wr.add_register(S32(40366, 3, "Inverter.UtilCrvCfg.CrvPt2.YVal", "Y-Werte der Kennlinie 2"))
    wr.add_register(S32(40368, 3, "Inverter.UtilCrvCfg.CrvPt2.YVal", "Y-Werte der Kennlinie 2"))
    wr.add_register(S32(40378, 3, "Inverter.UtilCrvCfg.CrvPt3.XVal", "X-Werte der Kennlinie 3"))
    wr.add_register(S32(40380, 3, "Inverter.UtilCrvCfg.CrvPt3.XVal", "X-Werte der Kennlinie 3"))
    wr.add_register(S32(40382, 3, "Inverter.UtilCrvCfg.CrvPt3.XVal", "X-Werte der Kennlinie 3"))
    wr.add_register(S32(40384, 3, "Inverter.UtilCrvCfg.CrvPt3.XVal", "X-Werte der Kennlinie 3"))
    wr.add_register(S32(40386, 3, "Inverter.UtilCrvCfg.CrvPt3.XVal", "X-Werte der Kennlinie 3"))
    wr.add_register(S32(40388, 3, "Inverter.UtilCrvCfg.CrvPt3.XVal", "X-Werte der Kennlinie 3"))
    wr.add_register(S32(40390, 3, "Inverter.UtilCrvCfg.CrvPt3.XVal", "X-Werte der Kennlinie 3"))
    wr.add_register(S32(40392, 3, "Inverter.UtilCrvCfg.CrvPt3.XVal", "X-Werte der Kennlinie 3"))
    wr.add_register(S32(40402, 3, "Inverter.UtilCrvCfg.CrvPt3.YVal", "Y-Werte der Kennlinie 3"))
    wr.add_register(S32(40404, 3, "Inverter.UtilCrvCfg.CrvPt3.YVal", "Y-Werte der Kennlinie 3"))
    wr.add_register(S32(40406, 3, "Inverter.UtilCrvCfg.CrvPt3.YVal", "Y-Werte der Kennlinie 3"))
    wr.add_register(S32(40408, 3, "Inverter.UtilCrvCfg.CrvPt3.YVal", "Y-Werte der Kennlinie 3"))
    wr.add_register(S32(40410, 3, "Inverter.UtilCrvCfg.CrvPt3.YVal", "Y-Werte der Kennlinie 3"))
    wr.add_register(S32(40412, 3, "Inverter.UtilCrvCfg.CrvPt3.YVal", "Y-Werte der Kennlinie 3"))
    wr.add_register(S32(40414, 3, "Inverter.UtilCrvCfg.CrvPt3.YVal", "Y-Werte der Kennlinie 3"))
    wr.add_register(S32(40416, 3, "Inverter.UtilCrvCfg.CrvPt3.YVal", "Y-Werte der Kennlinie 3"))
    wr.add_register(U32(40428, 3, "GridGuard.Cntry.FrqCtl.hhLim", "Frequenzüberwachung mittlere Maximalschwelle"))
    wr.add_register(U32(40430, 3, "GridGuard.Cntry.FrqCtl.hhLimTmms", "Frequenzüberwachung mittlere Maximalschwelle Auslösezeit"))
    wr.add_register(U32(40432, 3, "GridGuard.Cntry.FrqCtl.hLim", "Frequenzüberwachung untere Maximalschwelle"))
    wr.add_register(U32(40434, 3, "GridGuard.Cntry.FrqCtl.hLimTmms", "Frequenzüberwachung untere Maximalschwelle Auslösezeit"))
    wr.add_register(U32(40436, 3, "GridGuard.Cntry.FrqCtl.lLim", "Frequenzüberwachung obere Minimalschwelle"))
    wr.add_register(U32(40438, 3, "GridGuard.Cntry.FrqCtl.lLimTmms", "Frequenzüberwachung obere Minimalschwelle Auslösezeit"))
    wr.add_register(U32(40440, 3, "GridGuard.Cntry.FrqCtl.llLim", "Frequenzüberwachung mittlere Minimalschwelle"))
    wr.add_register(U32(40442, 3, "GridGuard.Cntry.FrqCtl.llLimTmms", "Frequenzüberwachung mittlere Minimalschwelle Auslösezeit"))
    wr.add_register(U32(40446, 3, "GridGuard.Cntry.VolCtl.MaxTmms", "Spannungsüberwachung obere Maximalschwelle Auslösezeit"))
    wr.add_register(U32(40448, 3, "GridGuard.Cntry.VolCtl.hhLim", "Spannungsüberwachung mittlere Maximalschwelle"))
    wr.add_register(U32(40450, 3, "GridGuard.Cntry.VolCtl.hhLimTmms", "Spannungsüberwachung mittlere Maximalschwelle Auslösezeit"))
    wr.add_register(U32(40452, 3, "GridGuard.Cntry.VolCtl.hLim", "Spannungsüberwachung untere Maximalschwelle"))
    wr.add_register(U32(40456, 3, "GridGuard.Cntry.VolCtl.hLimTmms", "Spannungsüberwachung untere Maximalschwelle Auslösezeit"))
    wr.add_register(U32(40458, 3, "GridGuard.Cntry.VolCtl.lLim", "Spannungsüberwachung obere Minimalschwelle"))
    wr.add_register(U32(40462, 3, "GridGuard.Cntry.VolCtl.lLimTmms", "Spannungsüberwachung obere Minimalschwelle Auslösezeit"))
    wr.add_register(U32(40464, 3, "GridGuard.Cntry.VolCtl.llLim", "Spannungsüberwachung mittlere Minimalschwelle"))
    wr.add_register(U32(40466, 3, "GridGuard.Cntry.VolCtl.llLimTmms", "Spannungsüberwachung mittlere Minimalschwelle Auslösezeit"))
    wr.add_register(U32(40472, 3, "Inverter.PlntCtl.VRef", "Referenzspannung"))
    wr.add_register(S32(40474, 3, "Inverter.PlntCtl.VRefOfs", "Referenzkorrekturspannung"))
    wr.add_register(U32(40480, 3, "Nameplate.ARtg", "Nennstrom über alle Phasen"))
    wr.add_register(U32(40482, 3, "Inverter.VArGra", "Blindleistungsgradient"))
    wr.add_register(U32(40484, 3, "Inverter.WGraEna", "Aktivierung des Wirkleistungsgradienten"))
    wr.add_register(U32(40490, 3, "Inverter.VArModCfg.VArCtlVolCfg.VArGraNom", "Blindleistungsgradient, Konfiguration der Blindleistungs-/Spannungskennlinie Q(U)"))
    wr.add_register(STR32(40497, 3, "Nameplate.MacId", "-"))
    wr.add_register(STR32(40513, 3, "Spdwr.DnsSrvIp", "-"))
    wr.add_register(U32(40575, 3, "MltFncSw.OpMode", "Betriebsart des Multifunktionsrelais"))
    wr.add_register(U32(40577, 3, "MltFncSw.OpMode", "Betriebsart des Multifunktionsrelais"))
    wr.add_register(STR32(40631, 3, "Nameplate.Location", "-"))
    wr.add_register(U32(40647, 3, "Upd.AutoUpdIsOn", "Automatische Updates eingeschaltet"))
    wr.add_register(U32(40789, 3, "Nameplate.ComRev", "Kommunikationsversion"))
    wr.add_register(U32(40791, 3, "Inverter.PlntCtl.IntvTmsMax", "Timeout für Kommunikationsfehlermeldung"))
    wr.add_register(U32(40855, 3, "Inverter.UtilCrvCfg.Crv0.RmpDec", "Kennlinie, Absenkungsrampe für Erreichung des Kennlinienarbeitspunktes"))
    wr.add_register(U32(40857, 3, "Inverter.UtilCrvCfg.Crv0.RmpDec", "Kennlinie, Absenkungsrampe für Erreichung des Kennlinienarbeitspunktes"))
    wr.add_register(U32(40859, 3, "Inverter.UtilCrvCfg.Crv0.RmpDec", "Kennlinie, Absenkungsrampe für Erreichung des Kennlinienarbeitspunktes"))
    wr.add_register(U32(40875, 3, "Inverter.UtilCrvCfg.Crv0.RmpInc", "Kennlinie, Steigerungsrampe für Erreichung des Kennlinienarbeitspunktes"))
    wr.add_register(U32(40877, 3, "Inverter.UtilCrvCfg.Crv0.RmpInc", "Kennlinie, Steigerungsrampe für Erreichung des Kennlinienarbeitspunktes"))
    wr.add_register(U32(40879, 3, "Inverter.UtilCrvCfg.Crv0.RmpInc", "Kennlinie, Steigerungsrampe für Erreichung des Kennlinienarbeitspunktes"))
    wr.add_register(U32(40895, 3, "Inverter.UtilCrvCfg.Crv0.CrvTms", "Kennlinie, Einstellzeit des Kennlinienarbeitspunktes"))
    wr.add_register(U32(40897, 3, "Inverter.UtilCrvCfg.Crv0.CrvTms", "Kennlinie, Einstellzeit des Kennlinienarbeitspunktes"))
    wr.add_register(U32(40899, 3, "Inverter.UtilCrvCfg.Crv0.CrvTms", "Kennlinie, Einstellzeit des Kennlinienarbeitspunktes"))
    wr.add_register(U32(40915, 3, "Inverter.WMax", "Eingestellte Wirkleistungsgrenze"))
    wr.add_register(U32(40917, 3, "Inverter.UtilCrvCfg.CrvModCfg.CrvNum", "Kennliniennummer, Konfiguration des Kennlinienmodus"))
    wr.add_register(U32(40919, 3, "Inverter.UtilCrvCfg.CrvModCfg.CrvNum", "Kennliniennummer, Konfiguration des Kennlinienmodus"))
    wr.add_register(U32(40921, 3, "Inverter.UtilCrvCfg.CrvModCfg.CrvNum", "Kennliniennummer, Konfiguration des Kennlinienmodus"))
    wr.add_register(U32(40937, 3, "Inverter.UtilCrvCfg.CrvModCfg.CrvEna", "Aktivierung der Kennlinie, Konfiguration des Kennlinienmodus"))
    wr.add_register(U32(40939, 3, "Inverter.UtilCrvCfg.CrvModCfg.CrvEna", "Aktivierung der Kennlinie, Konfiguration des Kennlinienmodus"))
    wr.add_register(U32(40941, 3, "Inverter.UtilCrvCfg.CrvModCfg.CrvEna", "Aktivierung der Kennlinie, Konfiguration des Kennlinienmodus"))
    wr.add_register(U32(40957, 3, "Inverter.UtilCrvCfg.Crv0.XRef", "Kennlinie X-Achsen Referenz"))
    wr.add_register(U32(40959, 3, "Inverter.UtilCrvCfg.Crv0.XRef", "Kennlinie X-Achsen Referenz"))
    wr.add_register(U32(40961, 3, "Inverter.UtilCrvCfg.Crv0.XRef", "Kennlinie X-Achsen Referenz"))
    wr.add_register(U32(40977, 3, "Inverter.UtilCrvCfg.Crv0.YRef", "Kennlinie Y-Achsen Referenz"))
    wr.add_register(U32(40979, 3, "Inverter.UtilCrvCfg.Crv0.YRef", "Kennlinie Y-Achsen Referenz"))
    wr.add_register(U32(40981, 3, "Inverter.UtilCrvCfg.Crv0.YRef", "Kennlinie Y-Achsen Referenz"))
    wr.add_register(U32(40997, 3, "Inverter.DGSModCfg.HystVolNom", "Hysteresespannung, Konfiguration der dynamischen Netzstützung"))
    wr.add_register(S32(40999, 3, "Inverter.VArModCfg.PFCtlComCfg.PFEEI", "Sollwert cos(Phi) gemäß EEI-Konvention"))
    wr.add_register(U32(41121, 3, "GridGuard.CntrySet", "Setze Ländernorm"))
    wr.add_register(U32(41123, 3, "GridGuard.Cntry.VolCtl.ReconMin", "Min. Spannung zur Wiederzuschaltung"))
    wr.add_register(U32(41125, 3, "GridGuard.Cntry.VolCtl.ReconMax", "Max. Spannung zur Wiederzuschaltung"))
    wr.add_register(U32(41127, 3, "GridGuard.Cntry.FrqCtl.ReconMin", "Untere Frequenz für Wiederzuschaltung"))
    wr.add_register(U32(41129, 3, "GridGuard.Cntry.FrqCtl.ReconMax", "Obere Frequenz für Wiederzuschaltung"))
    wr.add_register(U32(41131, 3, "DcCfg.StrVol", "minimale Spannung Eingang "))
    wr.add_register(U32(41133, 3, "DcCfg.StrVol", "minimale Spannung Eingang "))
    wr.add_register(U32(41155, 3, "DcCfg.StrTms", "Startverzögerung Eingang "))
    wr.add_register(U32(41157, 3, "DcCfg.StrTms", "Startverzögerung Eingang "))
    wr.add_register(U32(41169, 3, "GridGuard.Cntry.LeakRisMin", "Minimaler Isolationswiderstand"))
    wr.add_register(U32(41171, 3, "Metering.TotkWhOutSet", "Setze Gesamtertrag"))
    wr.add_register(U32(41173, 3, "Metering.TotOpTmhSet", "Setze Gesamte Betriebszeit am Netzanschlusspunkt"))
    wr.add_register(U32(41187, 3, "Inverter.CtlComCfg.CtlMsSrc", "Quelle der Referenzmessung zur Blind-/Wirkleistungsregelung"))
    wr.add_register(U32(41193, 3, "Inverter.CtlComCfg.WCtlCom.CtlComMssMod", "Betriebsart für ausbleibende Wirkleistungsbegrenzung"))
    wr.add_register(U32(41195, 3, "Inverter.CtlComCfg.WCtlCom.TmsOut", "Timeout für ausbleibende Wirkleistungsbegrenzung"))
    wr.add_register(U32(41197, 3, "Inverter.CtlComCfg.WCtlCom.FlbWNom", "Fallback Wirkleistungsbegrenzung P in % von WMax für ausbleibende Wirkleistungsbegrenzung"))
    wr.add_register(U32(41199, 3, "PCC.WMaxNom", "Eingestellte Wirkleistungsgrenze am Netzanschlusspunkt"))
    wr.add_register(U32(41203, 3, "Plnt.DcWRtg", "Anlagen-Nennleistung"))
    wr.add_register(S32(41215, 3, "Inverter.WModCfg.WCtlComCfg.FlbWSpt", "Fallback Leistung für Betriebsart WCtlCom"))
    wr.add_register(U32(41217, 3, "PCC.WMax", "Eingestellte Wirkleistungsgrenze am Netzanschlusspunkt"))
    wr.add_register(U32(41219, 3, "Inverter.CtlComCfg.VArCtlCom.CtlComMssMod", "Betriebsart für ausbleibende Blindleistungsregelung"))
    wr.add_register(U32(41221, 3, "Inverter.CtlComCfg.VArCtlCom.TmsOut", "Timeout für ausbleibende Blindleistungsregelung"))
    wr.add_register(S32(41223, 3, "Inverter.CtlComCfg.VArCtlCom.FlbVArNom", "Fallback Blindleistung Q in % von WMax für ausbleibende Blindleistungsregelung"))
    wr.add_register(U32(41225, 3, "Inverter.CtlComCfg.PFCtlCom.CtlComMssMod", "Betriebsart für ausbleibende cos Phi-Vorgabe"))
    wr.add_register(U32(41227, 3, "Inverter.CtlComCfg.PFCtlCom.TmsOut", "Timeout für ausbleibende cos Phi-Vorgabe"))
    wr.add_register(S32(41229, 3, "Inverter.CtlComCfg.PFCtlCom.FlbPF", "Fallback cos Phi für ausbleibende cos Phi-Vorgabe"))
    wr.add_register(U32(41253, 3, "Inverter.FstStop", "Schnellabschaltung"))
    wr.add_register(S16(41255, 3, "Inverter.WModCfg.WCtlComCfg.WNomPrc", "Normierte Wirkleistungsbegrenzung durch Anlagensteuerung"))
    wr.add_register(S16(41256, 3, "Inverter.VArModCfg.VArCtlComCfg.VArNomPrc", "Normierte Blindleistungsbegrenzung durch Anlagensteuerung"))
    wr.add_register(S32(41257, 3, "Inverter.VArModCfg.PFCtlComCfg.PFEEI", "Sollwert cos(Phi) gemäß EEI-Konvention"))
